on:
  workflow_dispatch:
jobs:
  check_commit_job:
    runs-on: ubuntu-latest
    name: A job that checks last commits
    steps:
      - name: check
        id: hello
        uses: orianshechter/deadman-notification@v1.1
        with:
          telegram_bot_token: '2027359016:AAHoslcA_aCvOO-PinbAIRkDWJFerNt2bJ4'
          chat_id: '@damAddressNotify'
