name: Validate JSON file on addressesGeoPoints

on:
  pull_request:
    branches:
      - 'main'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Validate addressesGeoPoints.json
        run: python -mjson.tool "addressesGeoPoints.json" > /dev/null

      - name: Validate cities
        run: python -mjson.tool "cities.json" > /dev/null

